import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, FileCheck2, ShieldCheck, Trophy, AlertCircle } from "lucide-react";
import { getStatisticsData, selectedSeason } from "@/lib/statistics-data";
import { getSeasonStats, koreaDate, reviewSeason } from "@/lib/statistics";
import { AwardCards, SeasonPicker, SeasonBadge, SeasonMetrics } from "@/components/StatisticsView";
import { finalizeSeason } from "@/app/season-actions";
export const dynamic = "force-dynamic";
export default async function Page({ searchParams }: { searchParams: Promise<{ season?: string; error?: string; saved?: string }> }) {
  const query = await searchParams, data = Object.assign(await getStatisticsData(), { admin: true }), season = selectedSeason(data.seasons,query.season);
  if (!season) return <p>시즌이 없습니다.</p>;
  const stats = getSeasonStats(data.leagues,season.id), review = reviewSeason(data.leagues,season.id);
  const dirty = season.finalized_at && season.revision !== season.finalized_revision;
  return <div className="admin-page season-page season-management"><header className="season-page-heading"><div><div className="season-breadcrumb"><Link href="/admin">관리자 홈</Link><ChevronRight size={14}/>시즌 관리</div><h1>시즌 관리</h1><p>한 시즌의 기록을 확인하고, 공식 타이틀을 확정하세요.</p></div><SeasonPicker data={data} season={season}/></header>
    <section className="season-overview"><div className="season-overview-copy"><span className="season-eyebrow">시즌 운영 현황</span><div><h2>{season.name}</h2><SeasonBadge season={season}/></div><p><CalendarDays size={16}/>{season.start_date} — {season.end_date}</p></div><Link className="season-outline-link" href={`/admin/statistics?season=${season.id}`}>시즌 통계 보기 <ArrowRight size={17}/></Link><SeasonMetrics players={stats.players.length} leagues={stats.leagues.length} games={stats.games}/></section>
    {query.error && <p role="alert" className="season-warning">{query.error}</p>}{query.saved && <p role="status">시즌 결과를 확정했습니다.</p>}
    {dirty && <p className="season-warning">⚠ 시즌 확정 이후 데이터가 변경되었습니다. 아래 기존 수상 결과와 재계산 결과, 리그 기록을 확인해 주세요.</p>}
    <section className="season-review-grid"><div className="card season-review-card"><div className="season-section-heading"><div><h2><ClipboardCheck size={22}/>확정 전 검수</h2><p>빠진 기록이 없는지 마지막으로 확인해 주세요.</p></div><span className={`review-pill ${review.canFinalize ? "ready" : "pending"}`}>{review.canFinalize ? "기록 검수 완료" : "확인 필요"}</span></div><div className="review-counters"><div><span>전체 경기</span><strong>{review.totalMatches}<small>경기</small></strong></div><div className={review.incomplete.length ? "needs-attention" : ""}><span>미완료 리그</span><strong>{review.incomplete.length}<small>회</small></strong></div><div className={review.missing ? "needs-attention" : ""}><span>결과 미입력</span><strong>{review.missing}<small>경기</small></strong></div></div>
      {!review.canFinalize && <p className="season-warning">시즌을 아직 확정할 수 없습니다. 미완료 데이터와 최종 순위를 확인해 주세요.</p>}
      <div className="review-leagues">{review.selected.map(l => <Link className="review-league-row" href={`/ops/${l.id}`} key={l.id}><span className="review-round">{l.round_number}</span><div><strong>제{l.round_number}회 일요리그</strong><span>{l.league_date} · 미입력 {l.matches.filter(m => !m.match_results).length}경기</span></div><span className={`review-pill ${l.status === "COMPLETED" ? "ready" : "pending"}`}>{l.status === "COMPLETED" ? "완료" : "미완료"}</span><ChevronRight size={17}/></Link>)}{!review.selected.length && <div className="records-empty"><CalendarDays size={28}/><strong>등록된 리그가 없습니다.</strong><p>시즌에 속한 리그가 이곳에 표시됩니다.</p></div>}</div>
    </div><aside className="card season-checklist"><span className="checklist-symbol"><ShieldCheck size={29}/></span><h2>확정 체크리스트</h2><p>모든 조건이 충족되면<br/>시즌 결과를 확정할 수 있어요.</p>{[{label:"모든 리그 완료",ok:!review.incomplete.length},{label:"모든 경기 결과 입력",ok:!review.missing},{label:"최종 순위 기록 확인",ok:!review.missingStandings.length},{label:"시즌 운영 기간 종료",ok:season.end_date < koreaDate()}].map(item => <div className={`checklist-item ${item.ok ? "done" : ""}`} key={item.label}>{item.ok ? <CheckCircle2 size={18}/> : <AlertCircle size={18}/>}<span>{item.label}</span></div>)}<small>순위 누락 리그 {review.missingStandings.length}회</small></aside></section>
    {season.finalized_at && <section><h2>기존 확정 결과</h2><AwardCards data={data} season={season}/></section>}
    <section><div className="season-section-heading"><div><h2><Trophy size={22}/>{season.finalized_at ? "재계산 결과" : "공식 칭호 미리보기"}</h2><p>공동 수상자를 포함한 최종 후보입니다.</p></div></div><AwardCards data={data} season={season} preview/></section>
    <form className="season-finalize-card" action={finalizeSeason}><div className="finalize-title"><FileCheck2 size={30}/><div><h2>{season.finalized_at ? "시즌 결과 재확정" : "이번 시즌의 기록을 완성하세요"}</h2><p>확정된 타이틀은 선수의 커리어에 기록됩니다.</p></div></div><input type="hidden" name="id" value={season.id}/><input type="hidden" name="revision" value={season.revision}/><label><input type="checkbox" name="confirmed" required/> <span>위 검수와 수상 결과를 확인했습니다{season.finalized_at ? ". 기존 공식 칭호 이력을 새 결과로 갱신합니다." : "."}</span></label><div className="finalize-action"><p>{season.end_date >= koreaDate() ? "시즌 기간이 종료된 후 확정할 수 있습니다." : !review.canFinalize ? "확인 필요한 기록을 모두 정리해 주세요." : "모든 기록이 준비되었습니다."}</p><button disabled={!review.canFinalize || season.end_date >= koreaDate()}><ShieldCheck size={18}/>{season.finalized_at ? "시즌 결과 재확정" : "시즌 결과 확정"}</button></div></form>
  </div>;
}
