import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CalendarDays, ChevronRight, Flame, History, Medal, Swords, Trophy, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { getStatisticsData, selectedSeason } from "@/lib/statistics-data";
import { awardLabels, getPlayerRelationships, getSeasonStats } from "@/lib/statistics";
import { formatDivision } from "@/lib/format";
import { PairRecords, PlayerLink, SeasonPicker } from "@/components/StatisticsView";
import { PlayerLeagueHistory } from "@/components/PlayerLeagueHistory";
export default async function PlayerProfilePage({ params, searchParams, admin = false }: { params: Promise<{ playerId: string }>; searchParams: Promise<{ season?: string; page?: string }>; admin?: boolean }) {
  const { playerId } = await params, query = await searchParams, data = Object.assign(await getStatisticsData(), { admin });
  const player = data.people.get(playerId);
  if (!player) notFound();
  const career = query.season === "career", season = selectedSeason(data.seasons, query.season);
  const stats = getSeasonStats(data.leagues, career ? undefined : season?.id), row = stats.players.find(p => p.id === playerId);
  const relations = getPlayerRelationships(stats.pairs, playerId);
  const titles = career ? data.awards.filter(a => a.player_id === playerId) : season?.finalized_at ? data.awards.filter(a => a.season_id === season.id && a.player_id === playerId) : stats.awards.filter(a => a.player_id === playerId);
  const history = row?.history ?? [];
  const profileHref = `${admin ? "/admin" : ""}/players/${playerId}`;
  return <main className="container season-page player-profile-page"><Link className="profile-back" href={admin ? "/admin/statistics" : "/"}><ArrowLeft size={17}/>{admin ? "시즌 통계로" : "메인 화면으로"}</Link><header className="player-profile-hero"><div className="profile-identity"><span className="profile-avatar" aria-hidden="true">{player.name.slice(0,1)}<span><UserRound size={16}/></span></span><div><span className="season-eyebrow">조&amp;애플 일요리그 · 선수 프로필</span><h1>{player.name}{player.division && <span className="division-tag">{formatDivision(player.division)}</span>}</h1><p>한 경기씩 쌓아온, 나만의 일요리그 이야기.</p></div></div><Trophy className="profile-watermark" size={128} strokeWidth={1}/><div className="profile-view-bar"><nav aria-label="선수 기록 범위"><Link aria-current={!career ? "page" : undefined} href={`${profileHref}?season=${season?.id ?? ""}`}><CalendarDays size={17}/>시즌 기록</Link><Link aria-current={career ? "page" : undefined} href={`${profileHref}?season=career`}><History size={17}/>통산 기록</Link></nav><SeasonPicker data={data} season={season} career={career}/></div></header>
    <section className="card profile-basic-records"><div className="season-section-heading"><div><h2><Flame size={22}/>{career ? "통산 기본 기록" : `${season?.name ?? "시즌"} 기본 기록`}</h2><p>{career ? "일요리그에서 쌓은 모든 순간을 모았어요." : "이번 시즌 완료된 리그를 기준으로 집계합니다."}</p></div><span className="profile-period">{career ? "전체 기간" : season?.name}</span></div><dl className="player-stat-grid">{([['참가',row?.appearances],['경기',row?.games],['승',row?.wins],['패',row?.losses],['우승',row?.championships]] as const).map(([label,value]) => <div key={label} className={label === "승" ? "stat-blue" : label === "우승" ? "stat-red" : ""}><dt>{label}</dt><dd>{value ?? 0}<small>{label === "참가" || label === "우승" ? "회" : label === "경기" ? "경기" : ""}</small></dd></div>)}<div><dt>승률</dt><dd>{row?.games ? (row.wins / row.games * 100).toFixed(1) : "0.0"}<small>%</small></dd></div></dl></section>
    {!career && titles.length > 0 && <section className="profile-title-strip"><Medal size={25}/><div><span>이번 시즌의 공식 칭호</span><div>{titles.map(t => <p key={t.award_type}>{awardLabels[t.award_type]} <small>{season?.finalized_at ? `${season.name} 수상` : "현재 선두"}</small></p>)}</div></div></section>}
    {career ? <section className="card profile-rival"><div className="season-section-heading"><div><h2><Swords size={23}/>통산 최고의 라이벌</h2><p>맞대결 10경기 이상 · 승수 차이, 경기 수 순</p></div></div><PairRecords data={data} pairs={relations.rivals}/></section> : <section><div className="season-highlights profile-relationships">{([['nemesis','😈 천적','나를 가장 많이 이긴 상대'],['favorite','😎 단골손님','내가 가장 많이 이긴 상대'],['frequent','🤝 가장 많이 만난 상대','리그에서 가장 자주 맞붙은 상대']] as const).map(([key,label,description]) => <article className="card" key={key}><h3>{label}</h3><p className="relationship-description">{description}</p>{relations[key].length ? relations[key].map(p => <div className="opponent-record" key={p.id}><strong><PlayerLink id={p.id} data={data}/><ArrowUpRight size={15}/></strong><p><b>{p.wins}승</b> {p.losses}패 <span>총 {p.games}경기</span></p></div>) : <p className="event-empty">아직 해당 기록이 없습니다.</p>}</article>)}<article className="card"><h3>🔄 복수 성공</h3><p className="relationship-description">패배 후 다음 맞대결에서 이긴 기록</p><div className="revenge-value">{relations.revenge}<small>회</small></div><details><summary>상대별 기록 보기</summary>{relations.opponents.filter(p => p.revenge > 0).map(p => <p key={p.id}><PlayerLink id={p.id} data={data}/> · {p.revenge}회</p>)}{!relations.revenge && <p className="muted">패배 후 다음 맞대결에서 이기면 기록됩니다.</p>}</details></article></div></section>}
    <section className="card profile-play-records"><div className="season-section-heading"><div><h2><Trophy size={22}/>개인 플레이 기록</h2><p>나의 플레이를 보여주는 다섯 가지 기록.</p></div></div><dl className="player-stat-grid">{([['💯 전승 우승',row?.undefeated],['🥈 준우승',row?.runnersUp],['😱 풀세트 경기',row?.fullSets],['🧹 깔끔한 승리',row?.cleanWins],['🔁 최고 연속 우승',row?.streak]] as const).map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value ?? 0}<small>회</small></dd></div>)}</dl></section>
    {career && <><section className="card"><div className="season-section-heading"><div><h2><Medal size={22}/>획득한 시즌 타이틀</h2><p>시즌이 지나도 영원히 남는 나의 명예.</p></div></div><div className="career-awards">{(Object.keys(awardLabels) as (keyof typeof awardLabels)[]).map(type => { const awards = data.awards.filter(a => a.player_id === playerId && a.award_type === type); return <div key={type}><h3>{awardLabels[type]}</h3><strong>{awards.length}<small>회</small></strong><div>{awards.map(a => <Link key={a.id} href={`${profileHref}?season=${a.season_id}`}>{data.seasons.find(s => s.id === a.season_id)?.name}<ChevronRight size={13}/></Link>)}</div></div>; })}</div></section>
    <section className="card"><h2>시즌별 커리어 기록</h2>{data.seasons.map(s => { const record = getSeasonStats(data.leagues,s.id).players.find(p => p.id === playerId); if (!record) return null; return <div className="season-history-row" key={s.id}><Link href={`${profileHref}?season=${s.id}`}><strong>{s.name}</strong><p>{record.appearances}회 참가 · {record.wins}승 {record.losses}패 · 우승 {record.championships}회</p></Link><p>{data.awards.filter(a => a.season_id === s.id && a.player_id === playerId).map(a => awardLabels[a.award_type]).join(" · ")}</p></div>; })}</section></>}
    <section className="card profile-history"><div className="season-section-heading"><div><h2><History size={22}/>리그별 참가 이력</h2><p>그날의 경기와 결과를 다시 만나보세요.</p></div><span className="event-count">{history.length}회</span></div>{history.length ? <PlayerLeagueHistory key={career ? "career" : season?.id} history={history}/> : <div className="records-empty"><CalendarDays size={30}/><strong>완료된 리그 참가 기록이 없습니다.</strong><p>첫 리그를 마치면 이곳에 기록이 쌓입니다.</p></div>}</section>
  </main>;
}
